// Generated by CoffeeScript 1.6.2
(function() {
  describe("Browser HTTP Client", function() {
    describe("Bare", function() {
      it("should 'HEAD'");
      it("should 'OPTIONS'");
      it("should 'GET'");
      it("should 'POST'");
      it("should 'PUT'");
      return it("should 'DELETE'");
    });
    describe("Angular", function() {
      it("should 'HEAD'");
      it("should 'OPTIONS'");
      it("should 'GET'");
      it("should 'POST'");
      it("should 'PUT'");
      return it("should 'DELETE'");
    });
    return describe("jQuery", function() {
      it("should 'HEAD'");
      it("should 'OPTIONS'");
      it("should 'GET'");
      it("should 'POST'");
      it("should 'PUT'");
      return it("should 'DELETE'");
    });
  });

}).call(this);
