// Generated by CoffeeScript 1.6.2
(function() {
  describe("Node HTTP Client", function() {
    it("should 'HEAD'");
    it("should 'OPTIONS'");
    it("should 'GET'");
    it("should 'POST'");
    it("should 'PUT'");
    return it("should 'DELETE'");
  });

}).call(this);
