// Generated by CoffeeScript 1.6.2
(function() {
  angular.module('Collection').provider('Link', function() {
    return {
      $get: function() {
        var Link;

        return Link = (function() {
          function Link(_link) {
            this._link = _link;
          }

          Link.prototype.href = function() {
            return this._link.href;
          };

          Link.prototype.rel = function() {
            return this._link.rel;
          };

          Link.prototype.prompt = function() {
            return this._link.prompt;
          };

          Link.prototype.follow = function(done) {
            var options;

            if (done == null) {
              done = function() {};
            }
            options = {};
            return http.get(this._link.href, options, function(error, collection) {
              if (error) {
                return done(error);
              }
              return client.parse(collection, done);
            });
          };

          return Link;

        })();
      }
    };
  });

}).call(this);
