// Generated by CoffeeScript 1.6.2
(function() {
  angular.module('Collection').provider('Query', function() {
    return {
      $get: function() {
        var Query;

        return Query = (function() {
          function Query() {}

          Query = (function() {
            function Query(_query, form) {
              var _form;

              this._query = _query;
              this.form = form != null ? form : {};
              _query = this._query;
              _form = this.form;
              _.each(_query.data, function(datum) {
                if (_form[datum.name] == null) {
                  return _form[datum.name] = datum.value;
                }
              });
            }

            Query.prototype.datum = function(key) {
              var datum;

              datum = _.find(this._query.data || [], function(datum) {
                return datum.name === key;
              });
              return _.clone(datum);
            };

            Query.prototype.get = function(key) {
              return this.form[key];
            };

            Query.prototype.set = function(key, value) {
              return this.form[key] = value;
            };

            Query.prototype.promptFor = function(key) {
              var _ref;

              return (_ref = this.datum(key)) != null ? _ref.prompt : void 0;
            };

            Query.prototype.href = function() {
              return this._query.href;
            };

            Query.prototype.rel = function() {
              return this._query.rel;
            };

            Query.prototype.prompt = function() {
              return this._query.prompt;
            };

            Query.prototype.submit = function(done) {
              var options;

              if (done == null) {
                done = function() {};
              }
              options = {
                qs: this.form
              };
              return http.get(this._query.href, options, function(error, collection) {
                if (error) {
                  return done(error);
                }
                return client.parse(collection, done);
              });
            };

            return Query;

          })();

          return Query;

        })();
      }
    };
  });

}).call(this);
