// Generated by CoffeeScript 1.6.2
(function() {
  angular.module('Collection', []).factory('cj', function(Collection) {
    var ret;

    ret = function(href, options, done) {
      if (typeof options === 'function') {
        done = options;
        options = {};
      }
      return http.get(href, options, function(error, collection) {
        if (error) {
          return done(error);
        }
        return module.exports.parse(collection, done);
      });
    };
    ret.parse = function(collection, done) {
      var collectionObj, e, error, _error;

      if (done == null) {
        throw new Error("Callback must be passed to parse");
      }
      if (collection == null) {
        return done();
      }
      if (typeof collection === "string") {
        try {
          collection = JSON.parse(collection);
        } catch (_error) {
          e = _error;
          e.body = collection;
          console.log(e.body);
          done(e);
        }
      }
      collectionObj = null;
      try {
        collectionObj = new Collection(collection);
      } catch (_error) {
        e = _error;
        e.body = JSON.stringify(collection);
        return done(e);
      }
      error = null;
      if (_error = collectionObj.error) {
        error = new Error;
        error.title = _error.title;
        error.message = _error.message;
        error.code = _error.code;
        error.body = JSON.stringify(collection);
      }
      return done(error, collectionObj);
    };
    return ret;
  });

}).call(this);
