// Generated by CoffeeScript 1.6.2
(function() {
  describe("defineNested service", function() {
    var defineNested;

    defineNested = null;
    beforeEach(module('Collection'));
    beforeEach(inject(function(_defineNested_) {
      return defineNested = _defineNested_;
    }));
    it('defines nested properties on an object', function() {
      var expected, obj, stored;

      obj = {};
      expected = 'foo';
      stored = null;
      defineNested(obj, ['foo', 'bar', 'baz'], {
        get: function() {
          return expected;
        },
        set: function(v) {
          return stored = v;
        }
      });
      expect(obj.foo.bar.baz).toEqual(expected);
      obj.foo.bar.baz = 'zing';
      return expect(stored).toEqual('zing');
    });
    return it('supports multiple properties with same nested root', function() {
      var obj;

      obj = {};
      defineNested(obj, ['foo', 'bar', 'baz'], {
        get: function() {
          return 'one';
        }
      });
      defineNested(obj, ['foo', 'bar', 'qux'], {
        get: function() {
          return 'two';
        }
      });
      expect(obj.foo.bar.baz).toEqual('one');
      return expect(obj.foo.bar.qux).toEqual('two');
    });
  });

}).call(this);
