// Generated by CoffeeScript 1.6.2
(function() {
  describe("sealNested service", function() {
    var sealNested;

    sealNested = null;
    beforeEach(module('Collection'));
    beforeEach(inject(function(_sealNested_) {
      return sealNested = _sealNested_;
    }));
    return it('seals nested properties on an object', function() {
      var obj;

      obj = {
        foo: {
          bar: {
            baz: 'qux'
          }
        }
      };
      sealNested(obj, ['foo', 'bar', 'baz']);
      obj.foo.bar.zing = 'xxx';
      expect(obj.foo.bar.zing).toBeUndefined();
      obj.foo.bar.other = 'xxx';
      return expect(obj.foo.bar.other).toBeUndefined();
    });
  });

}).call(this);
